trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingsystem:  ubuntu-latest
#     mac:  
#       operatingsystem:  macos-latest

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: build
        steps:
          - bash: echo  "building"
  - stage: DevDeploy
    jobs:
    - deployment: DevDeploymentJob
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo deploy to dev
