# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage:  Build
  jobs:
  - job:  firstjob
    steps:
    - bash: echo Build firstjob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: pwd
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
# - stage:  DevDeploy
#   jobs:
#   - job:  secondjob
#     steps:
#     - bash: echo secondjob
# - stage:  QADeploy
#   jobs:
#   - job:  thirdjob
#     steps:
#     - bash: echo Build qadeployjob
# - stage:  ProdDeploy
#   jobs:
#   - job:  fourthjob
#     steps:
#     - bash: echo Build prodjob
