# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage:  Build
  jobs:
  - job:  firstjob
    steps:
    - bash: echo Build firstjob
- stage:  DevDeploy
  jobs:
  - job:  devdeploy job
    steps:
    - bash: echo Build devdeploy job
- stage:  QADeploy
  jobs:
  - job:  qadeploy job
    steps:
    - bash: echo Build qadeployjob
- stage:  ProdDeploy
  jobs:
  - job:  prod job
    steps:
    - bash: echo Build prod job
